# Generated by Django 3.2.9 on 2022-02-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(choices=[('020', '020'), ('019', '019'), ('018', '018'), ('017', '017'), ('016', '016'), ('015', '015')], max_length=10)),
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('live', models.CharField(max_length=100)),
                ('liveWS', models.CharField(choices=[('داخلية الوسط', 'داخلية الوسط'), ('داخلية ابودجانة', 'داخلية ابودجانة'), ('داخلية النيل الابيض', 'داخلية النيل الابيض'), ('مجمع الزهراء', 'مجمع الزهراء'), ('داخلية اخرى', 'داخلية اخرى'), ('لا اسكن داخلية', 'لا اسكن داخلية')], max_length=20)),
                ('fatherStatus', models.CharField(choices=[('متوفي', 'متوفي'), ('على قيد الحياة', 'على قيد الحياة')], max_length=15)),
                ('motherStatus', models.CharField(choices=[('متوفية', 'متوفية'), ('على قيد الحياة', 'على قيد الحياة')], max_length=15)),
                ('famIncome', models.CharField(choices=[('عالي', 'عالي'), ('متوسط', 'متوسط'), ('متدني', 'متدني')], max_length=10)),
                ('income', models.CharField(choices=[('اقل من الرسوم الدراسية', 'اقل من الرسوم الدراسية'), ('مساوي للرسوم الدراسية', 'مساوي للرسوم الدراسية'), ('اعلى من الرسوم الدراسية', 'اعلى من الرسوم الدراسية')], max_length=30)),
                ('brotherNum', models.IntegerField()),
                ('workAndStudy', models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=10)),
                ('howPay', models.CharField(choices=[('انت', 'انت'), ('ولي الامر', 'ولي الامر'), ('مصادر اخرى', 'مصادر اخرى')], max_length=20)),
                ('hardPay', models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا'), ('ربما', 'ربما')], max_length=10)),
                ('timeSemiPay', models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=10)),
                ('costAndPay', models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا'), ('ربما', 'ربما')], max_length=10)),
                ('enoughCost', models.CharField(choices=[('تكفي لمنصرفات اليوم و زيادة', 'تكفي لمنصرفات اليوم و زيادة'), ('تكفي لمنصرفات اليوم فقط', 'تكفي لمنصرفات اليوم فقط'), ('لا تكفي لمنصرفات اليوم', 'لا تكفي لمنصرفات اليوم')], max_length=30)),
                ('engTool', models.CharField(choices=[('مناسبة', 'مناسبة'), ('غير مناسبة', 'غير مناسبة')], max_length=15)),
                ('socialBox', models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا')], max_length=10)),
                ('supportBox', models.CharField(choices=[('نعم', 'نعم'), ('لا', 'لا'), ('لا اعرف', 'لا اعرف')], max_length=10)),
                ('boxMony', models.CharField(choices=[('شهري 500 جنيه', 'شهري 500 جنيه'), ('اسبوعي 100 جنيه', 'اسبوعي 100 جنيه')], max_length=30)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
